name: CI

on:
  schedule:
    - cron:  '*/5 * * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: |
          git config user.name robopsy
          git config user.email hey@robopsycholo.gy
          git commit --allow-empty -m "Always Green!"
          git push
